### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by laoquanshi** [j3ers3/Hello-Java-Sec#14]
![image](https://github.com/j3ers3/Hello-Java-Sec/assets/110451039/ab30b433-e1a0-407e-903f-0b198bb06ead)
登录界面输入的账号密码 没错啊 为啥登录失败啊 我丢

**Comment by j3ers3** [comment]
账号写在代码里，再检查一下：https://github.com/j3ers3/Hello-Java-Sec/blob/master/src/main/java/com/best/hello/controller/Login.java
