### ISSUE TITLE
LDAP health check failed

### ISSUE THREAD

**Issue by kevinbbjj** [j3ers3/Hello-Java-Sec#16]
o.s.b.actuate.ldap.LdapHealthIndicator   : LDAP health check failed

org.springframework.ldap.CommunicationException: localhost:389; nested exception is javax.naming.CommunicationException: localhost:389 [Root exception is java.net.ConnectException: Connection refused: connect] 
at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:108) ~[spring-ldap-core-2.3.3.RELEASE.jar:2.3.3.RELEASE]

**Comment by j3ers3** [comment]
应该是关闭LDAP check的，在application.properties里加上management.health.ldap.enabled=false
