### ISSUE TITLE
docker中运行错误

### ISSUE THREAD

**Issue by 1822871719** [j3ers3/Hello-Java-Sec#3]
# docker 运行不了

```
---> 6881a357f8b7
Successfully built 6881a357f8b7
Successfully tagged javasec:latest
f020510cc8ffd6812699b2c2c9f1ffd099aac6d95cdc151b309c40a5c3dced95
(base) zqx@ubuntu:~/Documents/Hello-Java-Sec$ docker ps 
WARNING: Error loading config file: /home/zqx/.docker/config.json: open /home/zqx/.docker/config.json: permission denied
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
(base) zqx@ubuntu:~/Documents/Hello-Java-Sec$ 
```
开始是找不到jar包，然后我把下载的jar包改为javasec.jar
容器创建成功了，但是还是访问不了！

**Comment by why-git-why** [comment]
我在部署docker时也碰到了同样的问题
stat /var/lib/docker/tmp/docker-builder410261018/javasec.jar: no such file or directory

**Comment by zzzjoy-620** [comment]
外部访问不了是因为配置server.address = 127.0.0.1的问题，可以尝试改为server.address = 0.0.0.0

**Comment by why-git-why** [comment]
> 外部访问不了是因为配置server.address = 127.0.0.1的问题，可以尝试改为server.address = 0.0.0.0

作者你好，我不太明白你的意思，我的现在是找不到javasec.jar这个文件，配置server.address能解决吗，不好意思，我也是刚接触docker

**Comment by j3ers3** [comment]
> 我在部署docker时也碰到了同样的问题 stat /var/lib/docker/tmp/docker-builder410261018/javasec.jar: no such file or directory

Dockerfile里写的是`ADD javasec.jar`，请把jar包名字改成一样的

**Comment by j3ers3** [comment]
> .docker/config.json: permission denied

这个docker配置问题吧，自行百度

**Comment by Mzcifer** [comment]
师傅你好，想问一下在docker中已经部署成功，容器内部可以访问，但是容器外部无法访问，这种情况应该去哪里进行更改呢

**Comment by Mzcifer** [comment]
> > 我在部署docker时也碰到了同样的问题 stat /var/lib/docker/tmp/docker-builder410261018/javasec.jar: no such file or directory
> 
> Dockerfile里写的是`ADD javasec.jar`，请把jar包名字改成一样的

师傅你好，想问一下在docker中已经部署成功，容器内部可以访问，但是容器外部无法访问，这种情况应该去哪里进行更改呢

**Comment by why-git-why** [comment]
> # docker 运行不了
> ```
> ---> 6881a357f8b7
> Successfully built 6881a357f8b7
> Successfully tagged javasec:latest
> f020510cc8ffd6812699b2c2c9f1ffd099aac6d95cdc151b309c40a5c3dced95
> (base) zqx@ubuntu:~/Documents/Hello-Java-Sec$ docker ps 
> WARNING: Error loading config file: /home/zqx/.docker/config.json: open /home/zqx/.docker/config.json: permission denied
> CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
> (base) zqx@ubuntu:~/Documents/Hello-Java-Sec$ 
> ```
> 
> 开始是找不到jar包，然后我把下载的jar包改为javasec.jar 容器创建成功了，但是还是访问不了！

师傅你好，你的这个jar包从哪里下载的，是要单独在docker中布置java环境吗，还是它在下载这个镜像的时候已经下载好jar包，只需要更改名字就可以了

**Comment by Mzcifer** [comment]
> > # docker 运行不了
> > ```
> > ---> 6881a357f8b7
> > Successfully built 6881a357f8b7
> > Successfully tagged javasec:latest
> > f020510cc8ffd6812699b2c2c9f1ffd099aac6d95cdc151b309c40a5c3dced95
> > (base) zqx@ubuntu:~/Documents/Hello-Java-Sec$ docker ps 
> > WARNING: Error loading config file: /home/zqx/.docker/config.json: open /home/zqx/.docker/config.json: permission denied
> > CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
> > (base) zqx@ubuntu:~/Documents/Hello-Java-Sec$ 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 开始是找不到jar包，然后我把下载的jar包改为javasec.jar 容器创建成功了，但是还是访问不了！
> 
> 师傅你好，你的这个jar包从哪里下载的，是要单独在docker中布置java环境吗，还是它在下载这个镜像的时候已经下载好jar包，只需要更改名字就可以了

releases中有一个jar文件，下载后将名字改为Dockerfile中写的名字，即javasec.jar即可

**Comment by why-git-why** [comment]
> 师傅你好，想问一下在docker中已经部署成功，容器内部可以访问，但是容器外部无法访问，这种情况应该去哪里进行更改呢

谢谢师傅，那个jar包的问题，我太粗心了们没有好好看readme文件，感谢
