### ISSUE TITLE
建议进一步增加水平越权

### ISSUE THREAD

**Issue by k4n5ha0** [j3ers3/Hello-Java-Sec#5]
制作一个只有admin才能访问的接口，zhangwei的session不能访问
对应的制作一个和上面功能一致但对用户session不进行任何判断的接口
让学习者可以用bp测水平越权

**Comment by j3ers3** [comment]
https://github.com/j3ers3/Hello-Java-Sec/blob/master/src/main/java/com/best/hello/controller/IDOR/
